name: Daily Python Script

on:
  schedule:
    - cron: '45 19 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Update to the latest version (v2) of actions/checkout
      
      - name: Set up Python
        uses: actions/setup-python@v2  # Updated to v2 for Python 3.9
        with:
          python-version: '3.9'  # Replace with your desired Python version
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install gspread
          pip install oauth2client

      - name: Run Python script
        run: python main_script.py  # Replace with the name of your Python script
